spring:
 datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      package-to-scam: com.javanautas.fakeapius.infrastructure.entities
      format_sql: ture
      dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    loadbalancer:
      ribbon:
        enable: true

fake-api:
  url: https://fakestoreapi.com

server:
  port: 8181
