spring:
 datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      package-to-scam: com.evolue.plataformaanaliseevolueus.infrastructure.entities
      format_sql: ture
      dialect: org.hibernate.dialect.PostgreSQLDialect

fake-api:
  url: https://fakestoreapi.com

spring:
  cloud:
  loadbalancer:
  ribbon:
  enable: true

server:
  port: 8181
